import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  /* 배경색(backgroundColor)은 각 Screen 컴포넌트 내부에서 theme.bg로 직접 매핑합니다. */
  screen: { 
    flex: 1, 
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  headerBackBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: { 
    fontSize: 17, 
    fontWeight: '700',
  },
  scrollContent: { 
    padding: 20, 
    paddingBottom: 40,
  },
  /* 카드 배경색(backgroundColor)은 화면단에서 theme.card로 처리합니다. */
  card: { 
    borderRadius: 20, 
    overflow: 'hidden',
  },
  rowBorder: { 
    borderBottomWidth: 1, 
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    marginBottom: 8,
    paddingLeft: 4,
    letterSpacing: 0.5,
  },
  inputLabel: { 
    fontSize: 13, 
    fontWeight: '600', 
    marginBottom: 8,
  },
  input: {
    height: 52,
    borderRadius: 14,
    borderWidth: 1.5,
    fontSize: 15,
    paddingHorizontal: 16,
  },
  eyeBtn: { 
    position: 'absolute', 
    right: 14, 
    top: 0, 
    bottom: 0, 
    justifyContent: 'center', 
    padding: 4,
  },
  inputHint: { 
    fontSize: 12, 
    marginTop: 6,
  },
  textarea: {
    borderRadius: 14,
    borderWidth: 1.5,
    fontSize: 15,
    padding: 14,
    textAlignVertical: 'top',
    minHeight: 90,
  },
  charCount: { 
    textAlign: 'right', 
    fontSize: 12, 
    marginTop: 4,
  },
  /* 기본 버튼 색상 처리는 컴포넌트 내부에서 유동적으로 바인딩합니다. */
  primaryBtn: { 
    height: 54, 
    borderRadius: 16, 
    alignItems: 'center', 
    justifyContent: 'center',
  },
  primaryBtnText: { 
    fontSize: 16, 
    fontWeight: '700', 
    color: '#fff',
  },
  avatarContainer: { 
    alignItems: 'center', 
    marginBottom: 36,
  },
  avatarCircle: { 
    width: 96, 
    height: 96, 
    borderRadius: 48, 
    alignItems: 'center', 
    justifyContent: 'center',
  },
  avatarText: { 
    fontSize: 36, 
    color: '#fff', 
    fontWeight: '700',
  },
  cameraBtn: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  changePhotoText: { 
    marginTop: 12, 
    fontSize: 13, 
    fontWeight: '600',
  },
  infoBanner: { 
    borderRadius: 16, 
    padding: 16, 
    marginBottom: 28, 
    flexDirection: 'row', 
    gap: 12, 
    alignItems: 'flex-start',
  },
  infoBannerText: { 
    flex: 1, 
    fontSize: 13, 
    lineHeight: 20,
  },
  notifRow: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    justifyContent: 'space-between', 
    paddingHorizontal: 18, 
    paddingVertical: 16,
  },
  rowLabel: { 
    fontSize: 15, 
    fontWeight: '600',
  },
  rowSub: { 
    fontSize: 12, 
    marginTop: 2,
  },
  contactGrid: { 
    flexDirection: 'row', 
    gap: 10, 
    marginBottom: 28,
  },
  contactCard: { 
    flex: 1, 
    borderRadius: 18, 
    padding: 12, 
    alignItems: 'center', 
    gap: 8, 
    borderWidth: 1.5,
  },
  contactIconBox: { 
    width: 44, 
    height: 44, 
    borderRadius: 14, 
    alignItems: 'center', 
    justifyContent: 'center',
  },
  contactLabel: { 
    fontSize: 12, 
    fontWeight: '700', 
    textAlign: 'center',
  },
  contactSub: { 
    fontSize: 11, 
    textAlign: 'center',
  },
  faqRow: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    justifyContent: 'space-between', 
    padding: 16, 
    paddingHorizontal: 18,
  },
  chevronText: { 
    fontSize: 24, 
    lineHeight: 28,
  },
  faqAnswer: { 
    paddingHorizontal: 18, 
    paddingBottom: 16, 
    fontSize: 13, 
    lineHeight: 22,
  },
  appIconContainer: { 
    alignItems: 'center', 
    marginBottom: 36,
  },
  appIconBox: { 
    width: 88, 
    height: 88, 
    borderRadius: 28, 
    alignItems: 'center', 
    justifyContent: 'center', 
    marginBottom: 14,
  },
  appName: { 
    fontSize: 22, 
    fontWeight: '800',
  },
  appVersion: { 
    fontSize: 13, 
    marginTop: 4,
  },
  latestBadge: { 
    marginTop: 12, 
    paddingHorizontal: 14, 
    paddingVertical: 6, 
    borderRadius: 20,
  },
  latestBadgeText: { 
    fontSize: 12, 
    fontWeight: '700',
  },
  infoRow: { 
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    alignItems: 'center', 
    paddingHorizontal: 18, 
    paddingVertical: 15,
  },
  infoLabel: { 
    fontSize: 14, 
    fontWeight: '600',
  },
  infoValue: { 
    fontSize: 14, 
    fontWeight: '600',
  },
  linkRow: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    justifyContent: 'space-between', 
    paddingHorizontal: 18, 
    paddingVertical: 15,
  },
  linkIconBox: { 
    width: 36, 
    height: 36, 
    borderRadius: 10, 
    alignItems: 'center', 
    justifyContent: 'center',
  },
  linkLabel: { 
    fontSize: 15, 
    fontWeight: '600',
  },
  copyright: { 
    textAlign: 'center', 
    marginTop: 32, 
    fontSize: 12,
  },
  profileCard: {
    borderRadius: 22,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginBottom: 28,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  profileAvatar: { 
    width: 58, 
    height: 58, 
    borderRadius: 29, 
    alignItems: 'center', 
    justifyContent: 'center',
  },
  profileAvatarText: { 
    fontSize: 24, 
    color: '#fff', 
    fontWeight: '700',
  },
  profileName: { 
    fontSize: 17, 
    fontWeight: '700',
  },
  profileEmail: { 
    fontSize: 13, 
    marginTop: 2,
  },
  settingItem: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    paddingHorizontal: 18, 
    paddingVertical: 14,
  },
  settingIconBox: { 
    width: 40, 
    height: 40, 
    borderRadius: 13, 
    alignItems: 'center', 
    justifyContent: 'center',
  },
  settingLabel: { 
    fontSize: 15, 
    fontWeight: '600',
  },
  settingBadge: { 
    fontSize: 11, 
    fontWeight: '600', 
    marginTop: 1,
  },
});